#!/bin/bash
# Prompt with dmenu to copy emoji
# Dependencies: dmenu, xclip

cat $HOME/.scripts/emojis | dmenu -i -l 20 | awk '{ print $(NF) }' | xclip -selection clipboard
notify-send '${$(xclip -o)} copied to clipboard'
